### ISSUE TITLE
Could multi-process write the same file use boost.log?

### ISSUE THREAD

**Issue by mozeat-sun** [boostorg/log#106]
hi 
   i just not sure about the question,when i apply it in my project
  
   here is the case is :
   1). a dynamic library based on boost.log for logging message to a file ;
   2). multi-process will load the library at the same environment.

   my question is  when multi-process work the same time(log) ,can the file would be wrote correctly?

**Comment by Lastique** [comment]
Boost.Log does not support multiple processes writing to the same file or collecting their files to the same directory. You will have to write [your own sink backend](https://www.boost.org/doc/libs/1_72_0/libs/log/doc/html/log/extension.html#log.extension.sinks) that implements inter-process synchronization. Alternatively, you could use [inter-process communication](https://www.boost.org/doc/libs/1_72_0/libs/log/doc/html/log/detailed/sink_backends.html#log.detailed.sink_backends.text_ipc_message_queue) to collect log records from all your processes to a single logger process, which will then write them into files.
