### ISSUE TITLE
1.59 basic_formatting_ostream breaks on boost::format objects

### ISSUE THREAD

**Issue by nevion** [boostorg/log#11]
The operator<< overloads will fail to find a result for basic_format<char, std::char_traits<char>, std::allocator<char>>

Please advise/provide a patch -  I believe this might work but I do not have time to muck around this week on this

    basic_formatting_ostream& operator<< (boost::basic_format< char_type, traits_type >* formatter)
    {
        m_stream << buf;
        return *this;
    }

**Comment by Lastique** [comment]
See https://svn.boost.org/trac/boost/ticket/11549.
