### ISSUE TITLE
clang-10 warning: definition of implicit copy assignment operator is deprecated

### ISSUE THREAD

**Issue by k15tfu** [boostorg/log#118]
```
include/boost/log/attributes/attribute_set.hpp:176:9: error: definition of implicit copy assignment operator for 'iter<false>' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
        iter(iter< false > const& that) BOOST_NOEXCEPT : m_pNode(that.m_pNode) {}
        ^
/home/user/p/dotnet-products/3/Packages/JetBrains.boost.include.1.71.0.65/build/native/include/boost/log/attributes/scoped_attribute.hpp:82:27: note: in implicit copy assignment operator for 'boost::log::v2s_mt_posix::attribute_set::iter<false>' first required here
            m_itAttribute = res.first;
                          ^
```

**Comment by Lastique** [comment]
This is a bug in clang, as there is an explicitly defined assignment operator in this class. Please, report it to clang devs.

**Comment by k15tfu** [comment]
from https://en.cppreference.com/w/cpp/language/copy_assignment:
> A copy assignment operator of class T is a non-template non-static member function

@Lastique Sorry, I don't see such definition in `iter` class. Could you point me?

**Comment by Lastique** [comment]
It's not a copy assignment, it's an assignment operator defined here: https://github.com/boostorg/log/blob/c068c2a5aa94fcdcfe554414487e5d0d60e8a0e8/include/boost/log/attributes/attribute_set.hpp#L179

**Comment by k15tfu** [comment]
@Lastique I see you fixed it. So there was nothing to report to clang, yep?

**Comment by Lastique** [comment]
I added a workaround, but I still think clang is issuing a bogus warning.
