### ISSUE TITLE
exception with Syslog backend on Windows

### ISSUE THREAD

**Issue by zaphod71** [boostorg/log#119]
moved from boot 1.68.0 to 1.72 and newer. The logging to Syslog backerd on Windows platform causes an exception on new boost version (both toolsets). With 1.68.0 running without any issue.

Library is build with VS 2019 with different toolsets 1.40 and 1.41 with this build commands:

.\b2 --build-dir=c:\temp\build --stagedir=c:\temp\stage link=static --build-type=complete --toolset=msvc-14.0 stage --with-regex --with-filesystem --with-program_options --with-log 

and

.\b2 --build-dir=c:\temp\build --stagedir=c:\temp\stage link=static --build-type=complete --toolset=msvc-14.2 stage --with-regex --with-filesystem --with-program_options --with-log 

[boostlog_test.zip](https://github.com/boostorg/log/files/4540283/boostlog_test.zip)

![screenshot_20200427_164330](https://user-images.githubusercontent.com/64422359/80385383-4910ae00-88a6-11ea-93f2-5d5624a52efb.png)

**Comment by Lastique** [comment]
In my case I get an exception with `WSAHOST_NOT_FOUND` error code from Boost.ASIO. Indeed, I don't have the have a host named `marvin`.

You should catch the exception and check the error code you're getting.

**Comment by Lastique** [comment]
Also, note that you're not adding a MyLevel attribute anywhere. The attribute is used in the severity mapping function you're setting. This is not what is causing the exception, but a separate problem.

**Comment by zaphod71** [comment]
Of course, the host in in my network an with boost 1.68 this demo example is working. I copied the code from boost documentation:
https://www.boost.org/doc/libs/1_73_0_beta1/libs/log/doc/html/log/detailed/sink_backends.html#log.detailed.sink_backends.syslog

**Comment by Lastique** [comment]
In that case I can only recommend you to debug the issue. What error code are you getting? What is the exception backtrace?

**Comment by zaphod71** [comment]
It is a WINSOCK error:
WSAEAFNOSUPPORT (10047) Address family not supported by protocol family

But what changed from 1.68 to 1.72?

**Comment by Lastique** [comment]
Obviously, most libraries have changed. In this case, I believe, Boost.ASIO is the most relevant library.

I suspect, the error you're getting could be caused by mismatch of IP versions of the resolved address of the `marvin` host and the local address from which syslog messages are being sent. You're not setting any local address, so any local IPv4 interface is being used. Which means the `marvin` hostname resolving result has an IPv6 as the first entry.

I'm not sure what changed in Boost.ASIO or elsewhere. But you can fix this by explicitly setting local and target addresses with matching IP versions.

**Comment by zaphod71** [comment]
Yes,
it seems that the host name is resolved in a different way now. If the ip address is specified it works.

**Comment by Lastique** [comment]
I have added a fix that should restrict name resolution results to only the addresses with the IP version matching that which was specified on sink backend construction. You could try if that makes your original example work.
