### ISSUE TITLE
exception thrown at exit on multithreaded app, something is missing?

### ISSUE THREAD

**Issue by leobelen** [boostorg/log#124]
On a multithreaded app on macOS Catalina, with homebrewed boost 1.73,  and threads provided by std::thread an exception is thrown on exit that states 
``` 
uncaught exception of type boost::wrapexcept<boost::exception_detail::error_info_injector<boost::log::v2_mt_posix::system_error> >: Failed to set TLS value: Invalid argument
```
However, it is on the general winding down of the system, and the first line of the main function is path::imbue(std::locale("C")); and the last one is core::get()->remove_all_sinks();... is something missing?

**Comment by Lastique** [comment]
I can't tell what's going on without seeing the reproducer code. The exception is due to `pthread_setspecific` failure, which is likely because it is called on an invalid TLS key. This can happen if you're doing something with Boost.Log in global destructors.

**Comment by Lastique** [comment]
Any updates on this?

**Comment by Lastique** [comment]
No response.
