### ISSUE TITLE
documentation to filter-usage

### ISSUE THREAD

**Issue by tobias-loew** [boostorg/log#133]
Hi,

the documentation in detailed/utilities.html says to use

Filter="%Severity% > 3"

which is wrong: one must not use numbers for the severity-level but one of the names denoting them from the enum boost::log::trivial::severity_level

**Comment by Lastique** [comment]
No, the filter argument must correspond to the attribute value type that is actually used in log records. You can use any type as the severity level, including integers and enums, including ones defined by user. The example in the documentation is for an integer, which, BTW, is the default severity level type in `basic_severity_logger`.
