### ISSUE TITLE
Deadlock in asynchronous_sink::stop()

### ISSUE THREAD

**Issue by rcane** [boostorg/log#135]
The commit e0cb0b7 fixing #131 seems to have introduced a deadlock in the ```stop()``` method. The previous version of the code explicitly called ```queue_base_type::interrupt_dequeue()``` which stopped the blocking wait in ```run()```. Now this call is no longer made making ```stop()``` wait forever for ```join()``` to complete.

**Comment by Lastique** [comment]
Thanks for the report.
