### ISSUE TITLE
Use std::chrono for time measurements

### ISSUE THREAD

**Issue by ukreator** [boostorg/log#14]
It would be great to get rid of boost::date_time or at least use it as an optional component. For programs using std::chrono from c++11 or boost::chrono this boost::date_time dependency is just a waste of space in final product binaries.

**Comment by Lastique** [comment]
The dependency on Boost.DateTime won't be removed any time soon as it is used for obtaining timestamps. Chrono does not deal with that and as such it is not a suitable replacement.
