### ISSUE TITLE
error: debug_output_backend is not a member of sinks

### ISSUE THREAD

**Issue by RotateAt60MPH** [boostorg/log#148]
I'm trying to compile a x64-linux project under CentOS7 that has the following typedef in an #include (SystemConfiguration.h) file:

```
typedef sinks::synchronous_sink<sinks::debug_output_backend> sink_t;
```

I get the following compile error:

```
/home/Devel/Cores/generator/lib/Common/../Common/SystemConfiguration.h:130:40: error: âdebug_output_backendâ is not a member of âsinksâ
  130 | typedef sinks::synchronous_sink<sinks::debug_output_backend> sink_t;
      |                                        ^~~~~~~~~~~~~~~~~~~~
/home/Devel/Cores/generator/lib/Common/../Common/SystemConfiguration.h:130:60: error: template argument 1 is invalid
  130 | typedef sinks::synchronous_sink<sinks::debug_output_backend> sink_t;
      |                                                            ^

```

Boost::Log (1.75.0#1) came in as part of a vcpkg Boost package in both environments.  The identical code compiles and links fine under x64 Windows/Visual Studio 2019.  Both environment are using CMAKE with no explicit #defines that might affect Boost::Log that I can see.  On CentOS, I'm using gcc 9.3.1 to get some C++20 features.

Any advice appreciated.

**Comment by Lastique** [comment]
`debug_output_backend` is Windows-specific, it is not available on other systems.
