### ISSUE TITLE
1.59\58 conditional formatter + csv_decor fails

### ISSUE THREAD

**Issue by azerg** [boostorg/log#15]
Error compiling sample code in 1.59 & 1.58. At least 1.55 works fine

How to reproduce:
1. Open example code -> open log/example/basic_usage/main.cpp ( actually works anywhere )
2. Append next lines to formatter:
```
      << expr::if_(expr::contains(expr::smessage, "error"))
      [
        expr::stream << " an error msg: " << expr::csv_decor[expr::stream << expr::message]
      ]
      .else_
      [
        expr::stream << expr::csv_decor[expr::stream << expr::message]
      ]
```
3. The code wont compile, the first error is:
```..\formatters\char_decorator.hpp(320) : error C2039 : 'flush' : is not a member of 'boost::log::v2s_mt_nt5::expressions::aux::stream_ref<boost::log::v2s_mt_nt5::basic_formatting_ostream<char,std::char_traits<char>,std::allocator<char>>>'```

**Comment by Lastique** [comment]
Fixed in https://github.com/boostorg/log/commit/b7de827f231a61ad90c4305bfdc1b5453efc6071. Thanks for the report.
