### ISSUE TITLE
Build failure with MSVC with `BOOST_LOG_WITHOUT_SETTINGS_PARSERS`

### ISSUE THREAD

**Issue by Burgch** [boostorg/log#164]
When `BOOST_LOG_WITHOUT_SETTINGS_PARSERS` is defined, the `boost_log_setup` library doesn't export any symbols (because all of the C++ sources are basically empty after pre-processing). This results in MSVC (2019 in this case, using Boost 1.75) skipping the `.lib` generation entirely, which then results in:

```
The system cannot find the file specified.
...failed common.copy <path>\boost\lib\boost_log_setup-vc142-mt-x64-1_75.lib...
```

This led me to wonder whether there's even a need to build `boost_log_setup` at all when `BOOST_LOG_WITHOUT_SETTINGS_PARSERS` is defined? I have a proposed change which switches it between a library or an alias, depending on whether `BOOST_LOG_WITHOUT_SETTINGS_PARSERS` is defined or not - I'll create a pull request.

**Comment by Lastique** [comment]
This is currently blocked by https://github.com/bfgroup/b2/issues/104.
