### ISSUE TITLE
Log autolinks to DateTime

### ISSUE THREAD

**Issue by pdimov** [boostorg/log#166]
Here: https://github.com/boostorg/log/blob/d55f122f741b441e64b7f88bf1c3c4ed1d5d1feb/include/boost/log/detail/config.hpp#L254-L260

Since https://github.com/boostorg/log/commit/a79103cb3dedb6582d24a09e553874e0a5b5f6bc removed the dependency in build/Jamfile, installing Log with `b2 --with-log install` does not build and install the DateTime stub library. Consequently, autolinking to it fails, as in https://github.com/boostorg/boost_install/runs/4087219181?check_suite_focus=true.

**Comment by Lastique** [comment]
Fixed, thanks.

**Comment by pdimov** [comment]
Be sure to merge to master before today's deadline.

**Comment by Lastique** [comment]
Merged.
