### ISSUE TITLE
enum event_type seems to be wrong

### ISSUE THREAD

**Issue by humayunkhan** [boostorg/log#167]
In the following header file:
https://github.com/boostorg/log/blob/master/include/boost/log/sinks/event_log_constants.hpp

The enum:
//! Windows event types
    enum event_type
    {
        success = 0,                 //!< Equivalent to EVENTLOG_SUCCESS
        info = 4,                    //!< Equivalent to EVENTLOG_INFORMATION_TYPE
        warning = 2,                 //!< Equivalent to EVENTLOG_WARNING_TYPE
        error = 1                    //!< Equivalent to EVENTLOG_ERROR_TYPE
    };

is not correct in my opinion.

According to latest Microsoft documentation, valid values for event_type are 0, 1, 2 and 3  only.
Please refer to the following link to verify my claim:
https://docs.microsoft.com/en-in/windows/win32/eventlog/message-text-files#:~:text=message%20definition%20section.-,SeverityNames%3D,-(name%3Dnumber%5B%3Aname

The correct enum should be like this:
//! Windows event types
    enum event_type
    {
        success = 0,                 //!< Equivalent to EVENTLOG_SUCCESS
        info = 1,                    //!< Equivalent to EVENTLOG_INFORMATION_TYPE
        warning = 2,                 //!< Equivalent to EVENTLOG_WARNING_TYPE
        error = 3                    //!< Equivalent to EVENTLOG_ERROR_TYPE
    };

**Comment by Lastique** [comment]
`event_type` defines constants that are mentioned in the comments. These values are passed to [`ReportEvent`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-reporteventa) as `wType`. The values match `EVENTLOG_*` constants in Windows SDK, so they are correct.

**Comment by humayunkhan** [comment]
Hi.. Thanks for the clarification.

I need some help on https://github.com/boostorg/log/issues/169
Could you please look into it?
