### ISSUE TITLE
Linker error building Boost.Log with _WIN32_WINNT >= 0x0602

### ISSUE THREAD

**Issue by chrullrich** [boostorg/log#177]
Hello,

when using `/DBOOST_USE_WINAPI_VERSION=0x0602 /D_WIN32_WINNT=0x0602 /DWINVER=0x0602` or higher, the build of Boost.Log fails due to linker errors involving two missing symbols, `WaitOnAddress` and `WakeByAddressSingle`. These functions were introduced in Windows 8, i.e. 0x0602, and according to MSDN, their import library is `synchronization.lib`. This library is not mentioned on the linker command line or any build system files.

I added it to build/Jamfile.v2 and the library built successfully, but I'm far from an expert in Boost's build system. I'm also doing everything via vcpkg, which probably introduces even more unpredictability.

**Comment by Lastique** [comment]
The dependency on `synchronization.lib` is [added](https://github.com/boostorg/atomic/blob/8915f67c0e7ab8e2551570e7c5b1a9b98b902153/build/Jamfile.v2#L143) by Boost.Atomic, so Boost.Log inherits it when it is being built. User's code should either use to auto-linking, or should add linking with `synchronization.lib` on its own.

If you're not using official Boost build system then you must reproduce its behavior exactly in your own build system.

**Comment by Lastique** [comment]
I don't know how vcpkg works but if it implements its own build system then it needs to work like Boost.Build or Boost's CMake does. vcpkg team needs to investigate this on their end.

**Comment by pdimov** [comment]
vcpkg uses b2 to build Boost libraries.

**Comment by Lastique** [comment]
Then I'm not sure what the problem is. Boost.Log does build in our CI and Boost releases. I need a repro to go on.

**Comment by stephengtuggy** [comment]
> Then I'm not sure what the problem is. Boost.Log does build in our CI and Boost releases. I need a repro to go on.

A repro has been provided.

**Comment by stephengtuggy** [comment]
> Just in case if anyone is following this or finds this issue, if you have this issue and see "has synchronization.lib : no" at the beginning of your Boost build log, try running your build from the Visual Studio command line prompt.
> 
> Normally, Boost.Build should be able to detect Visual Studio paths and set up environment to run the compiler/linker, but apparently this may fail sometimes (possibly, when Visual Studio is installed in a non-default location). If you know a way for Boost.Build to improve detection for header/library paths, please report it to [Boost.Build](https://github.com/bfgroup/b2/).

Good to know, thanks.
