### ISSUE TITLE
undefined reference to boost::log::v2_mt_posix::basic_formatter

### ISSUE THREAD

**Issue by Heather** [boostorg/log#18]
getting this error on linux but everything works on visual studio

``` cmake
find_package(Boost 1.56.0 REQUIRED COMPONENTS ${USE_Boost_LIBRARIES} QUIET)
```

getting boost in superbuild with

``` cmake
list(APPEND _with_boost_libs --with-${USE_Boost_LIBRARIES})
```

and appealing it to b2

``` c++
undefined reference to `boost::log::v2_mt_posix::basic_formatter<char> boost::log::v2_mt_posix::parse_formatter<char>(char const*, char const*)'
```

I'm just including log library with cmake same way as other boost libraries.
I've found this thread http://sourceforge.net/p/boost-log/discussion/710022/thread/0524c8d3/ but what is boost_log_setup? is it separate boost library?

**Comment by Lastique** [comment]
Boost.Log builds into two libraries: boost_log and boost_log_setup, the latter depends on the former. The missing function in the linker error is in boost_log_setup. You should add it to the linker command line before boost_log.

**Comment by Heather** [comment]
arigato

**Comment by autosquid** [comment]
@Heather  I think I met the same problem, could I have a look at your related cmake file?

**Comment by Heather** [comment]
@autosquid I've used to add this library manually after compiling during linking 
`list(APPEND Boost_LIBRARIES boost_log_setup)`

**Comment by autosquid** [comment]
@Heather  no luck for me. As far as I see, cmake finds the right dylib of  `log_setup`, but still the link error exists in my case. The same code works for boost 1.58.0, but fails for 1.59.0

**Comment by autosquid** [comment]
The link error appears once I add the call of ```logging::add_file_log```

**Comment by Lastique** [comment]
There was a bug in 1.59 that has been fixed for 1.60. See https://github.com/boostorg/log/pull/10.

**Comment by autosquid** [comment]
@Lastique  OMG! Then what I can do to get around if I am installing 1.59 from homebrew? do a patch?

**Comment by Lastique** [comment]
You will have to build a patched version of Boost. I'm not sure how it works with homebrew, I'm not a Mac user.

**Comment by autosquid** [comment]
@Lastique  thanks, I'll patch it according to the P.R. you provide.
