### ISSUE TITLE
Boost.Log data is partially lost on reset or emergency shutdown

### ISSUE THREAD

**Issue by ikorneev** [boostorg/log#180]
Boost log loses some entries if OS crashes or is reset by user, that data is replaced by nulls
![image](https://user-images.githubusercontent.com/87642505/163399007-4472c69c-2a4f-486b-a51a-83b16e0df54f.png)
Though those entries were shown in log file, they are (30+ lines, about 2 minutes of logging) lost after reset like file was being edited but not saved. Auto_flush option doesn't help in this case.

Using text_file_backend, tried to set zero buf in implementation (by putting this `m_pImpl->m_File.rdbuf()->pubsetbuf(0, 0);` before `m_pImpl->m_File.open(...)` with no positive outcome.

Adding `FILE_FLAG_WRITE_THROUGH | FILE_FLAG_NO_BUFFERING` flags to CreateFile functions doesn't help too.

Any suggestions? Or is that by desing?

**Comment by Lastique** [comment]
As soon as Boost.Log hands off the formatted content to the OS, it is OS' responsibility to reliably store it. There is no case (short for hardware error) when Boost.Log corrupts the data it passes to the OS with zeros - it will either pass the buffered data it has, or it doesn't.

I think, what you're seeing is filesystem corruption. I do not see what Boost.Log can do about this, sorry.

> Adding `FILE_FLAG_WRITE_THROUGH | FILE_FLAG_NO_BUFFERING` flags to CreateFile functions doesn't help too.

Boost.Log doesn't call `CreateFile`, so I'm not sure what you did here.

**Comment by ikorneev** [comment]
OS - Windows 10 Pro, some other logs i used previously dont lose last logging info on that system (some of them lack rotation, though, which is good enough in boost). 
Honestly, i couldn't imagine that win10 is rarely-used system logging issues on which could be ignored that easy >_>

Well, could you help me by some clarification about log file creation?
It is created (if doesn't exist) when 
`m_pImpl->m_File.open(new_file_name, m_pImpl->m_FileOpenMode);'
is called, am i right? (for text file backend at least)

**Comment by Lastique** [comment]
> OS - Windows 10 Pro, some other logs i used previously dont lose last logging info on that system

I don't think this is information lost. I think it is more likely incorrect tracking of file size on system crash. If the file is open during the crash, the OS may not write the correct file size to the filesystem, which gets restored to whatever rounded up to the number of allocated sectors upon recovery.

You can try `multifile_text_backend`. That backend opens and closes the log file on each log record.

> It is created (if doesn't exist) when
> `m_pImpl->m_File.open(new_file_name, m_pImpl->m_FileOpenMode);`
> is called, am i right?

Yes.

**Comment by ikorneev** [comment]
Sadly, multiple_file_backend doesn't support rotation, which is kinda important part of logging lib i'm looking for. But perhaps with some tambourine-dancing...

**Comment by ikorneev** [comment]
@Lastique i've fixed this thing by calling close_file in the end of `text_file_backend::consume` (with 100ms+ between each to lessen disk overload). 
```
    if (m_pImpl->m_AutoFlush)
        m_pImpl->m_File.flush();    
    const auto mseconds_now = duration_cast<milliseconds>(system_clock::now().time_since_epoch()).count();
    if (mseconds_now-m_pImpl->m_last_closing_time>=100)
    {
        close_file();
        m_pImpl->m_last_closing_time = mseconds_now;
    }
```
Perhaps it's worth it to add some parameter like auto_flush to future versions (and timing attribute or counter between entries) to prevent such OS attitude?

**Comment by Lastique** [comment]
I don't think it's worth it. Ultimately, this is an OS issue, and that's where it should be fixed. Note that closing the file is not a 100% reliable solution, as there is still some amount of time when the file is open, and a system crash at this point could produce the same filesystem corruption.

What could be useful is to use low level system APIs to writing files instead of iostreams, with custom implementation of buffering. This would allow to make it more deterministic as to which data is passed to the OS and eliminate the possibility of a partial log record being passed to the OS. But this is not going to eliminate the possibility of filesystem corruption in case of a system crash, and Boost.Log is not going to be able to guarantee that anyway.

**Comment by ikorneev** [comment]
Well, it's better to lose last 1-2 log entries than 100-200 at least (or 100-200 instead of 1000-2000 etc, depends on log entries amount). However, i'm mot sure that Microsoft is going to fix this issue anywhere except Win11 too.
Thanks for pointing me to the right direction anyway!
