### ISSUE TITLE
compilation error in set_formatter method

### ISSUE THREAD

**Issue by BBID** [boostorg/log#194]
I'm trying to set the color using:
Sink->set_formatter(&coloring_formatter);
where coloring_formatter hat this signature:
	void  Logger::coloring_formatter(boost::log::record_view const &rec, boost::log::formatting_ostream &strm)
which semms to be a correct signature.
I get this error message when compiling:
Logger.cpp(56,51): error C2672: 'boost::log::v2_mt_nt6::sinks::basic_formatting_sink_frontend<char>::set_formatter': no matching overloaded function found
\include\boost-1_78\boost\log\sinks\basic_sink_frontend.hpp(374,10): message : could be 'void boost::log::v2_mt_nt6::sinks::basic_formatting_sink_frontend<char>::set_formatter(const FunT &)'

I cant also build it in linux as well and I dont see if where the problem is. could you please helm me with it?
Best Reagres,
Bahman

**Comment by Lastique** [comment]
If `Logger::coloring_formatter` is a non-`static` member function of `Logger` then you need to bind a pointer/reference to the `Logger` object on which this function should be called. For example:

```
class Logger
{
public:
    void coloring_formatter(boost::log::record_view const &rec, boost::log::formatting_ostream &strm);

    void init_logging()
    {
        // ...
        sink->set_formatter(std::bind(&Logger::coloring_formatter, this));
    }
};
```

Alternatively, if you don't need the `Logger` object in `coloring_formatter`, you can make it a `static` member function.

**Comment by BBID** [comment]
Thank you very much for your help! It worked!
