### ISSUE TITLE
CMake integration for Xcode universal 2 builds

### ISSUE THREAD

**Issue by EikeAtOT** [boostorg/log#220]
The current CMake implementation does not work on Xcode universal 2 builds (x86_64 and arm64) due to the way compiler flags are discovered and set. A universal build (where CMAKE_OSX_ARCHITECTURES = "x86_64;arm64") will fail when trying to compile dump_ssse3.cpp and dump_avx2.cpp

**Comment by Lastique** [comment]
Sorry, I have no experience with Xcode or Mac OS development and have no idea how universal builds work. You can consider this configuration untested and unsupported. PRs are welcome, although, again, I won't be able to test or maintain that configuration.
