### ISSUE TITLE
Missing example

### ISSUE THREAD

**Issue by heretic13** [boostorg/log#31]
Example folder cannot contain example with udp_socket_based for syslog_backend.

**Comment by heretic13** [comment]
No example & no test - > not caught bugs

**Comment by Lastique** [comment]
I'm not sure what you're saying but there are syslog and native_syslog examples. Converting either of them to UDP-based is trivial, I don't think there's a need for a separate example for that.

Regarding tests, Boost testing infrastructure is not really tailored for these kind of tests, hence no tests.
