### ISSUE TITLE
Test failure on msvc-14.1

### ISSUE THREAD

**Issue by pdimov** [boostorg/log#44]
```
compile-c-c++ ..\..\bin.v2\libs\log\test\util_ipc_reliable_mq.test\msvc-14.1\deb
ug\threadapi-win32\threading-multi\run\util_ipc_reliable_mq.obj
util_ipc_reliable_mq.cpp
C:\Projects\boost-git\boost\boost/thread/win32/thread_heap_alloc.hpp(25): error
C2039: 'HeapAlloc': is not a member of 'boost::detail::winapi'
C:\Projects\boost-git\boost\boost/log/utility/permissions.hpp(37): note: see dec
laration of 'boost::detail::winapi'
C:\Projects\boost-git\boost\boost/thread/win32/thread_heap_alloc.hpp(25): error
C2039: 'GetProcessHeap': is not a member of 'boost::detail::winapi'
C:\Projects\boost-git\boost\boost/log/utility/permissions.hpp(37): note: see dec
laration of 'boost::detail::winapi'
C:\Projects\boost-git\boost\boost/thread/win32/thread_heap_alloc.hpp(35): error
C2039: 'HeapFree': is not a member of 'boost::detail::winapi'
C:\Projects\boost-git\boost\boost/log/utility/permissions.hpp(37): note: see dec
laration of 'boost::detail::winapi'
C:\Projects\boost-git\boost\boost/thread/win32/thread_heap_alloc.hpp(35): error
C2039: 'GetProcessHeap': is not a member of 'boost::detail::winapi'
C:\Projects\boost-git\boost\boost/log/utility/permissions.hpp(37): note: see dec
laration of 'boost::detail::winapi'
```

**Comment by Lastique** [comment]
The errors are coming from Boost.Thread.

**Comment by pdimov** [comment]
Right, sorry. :-)

**Comment by pdimov** [comment]
Thread's tests don't fail though. :-)

**Comment by Lastique** [comment]
I think I found the problem. Boost.Thread accesses the symbols as `winapi::HeapAlloc`, which should normally resolve to `boost::winapi::HeapAlloc` or `boost::detail::winapi::HeapAlloc` (if the legacy Boost.WinAPI header is included). In Boost.Log, I had an outdated forward-declaration in `boost::detail::winapi` without including the legacy header, so the second name was used and there is no such symbol.

I have fixed the forward-declaration in 525c53b1a735f21d9b51d432b93a79f4f8b73c6b, which should fix the problem. However, the fact that Boost.Thread is implemented directly in namespace `boost` and `boost::detail` will likely cause us more headache in the future.

**Comment by pdimov** [comment]
I should close the Thread issue then?

**Comment by Lastique** [comment]
If it fixes the compilation, sure.

**Comment by Lastique** [comment]
Is this problem critical enough to request inclusion in 1.66?

**Comment by pdimov** [comment]
Yes, this fixes it. No, not critical at all. I just encountered it while testing the `boost-install` pull request as I run the tests before and after per Best Practices.
