### ISSUE TITLE
strange stdcerr file in 1.67 rc2

### ISSUE THREAD

**Issue by jeffreyscottgraham** [boostorg/log#51]
In the 1.67rc2 candidate an empty file called stdcerr is created at runtime in my unit tests.
Using boost log in 1.64 this file is not there.

**Comment by Lastique** [comment]
Can you provide a test case to reproduce the problem?

**Comment by Lastique** [comment]
BTW, a Boost-wide search only found one "stdcerr" string in Boost.Test:

https://github.com/boostorg/test/blob/master/include/boost/test/impl/framework.ipp#L916

Boost.Log does not create log files on its own, so I'm pretty sure this is where the file comes from. The string is probably a typo and should be "stderr", in which case the output should be written to the console.

**Comment by Lastique** [comment]
Please, report the bug to [Boost.Test](https://github.com/boostorg/test/issues/new).
