### ISSUE TITLE
Are there any plans to move Log from Boost types and functions to C++11 STL counterparts?

### ISSUE THREAD

**Issue by quixoticaxis** [boostorg/log#53]
For example, from `boost::shared_ptr` to `std::shared_ptr`. If not, are there any plans to generalize utility types and functions as template parameters, which would enable us to use both Boost and STL variants?

**Comment by Lastique** [comment]
There are no concrete plans and I wouldn't want Boost.Log to have a duplicated API for Boost and the standard library components. I think Boost.Log 2.x will keep its compatibility with C++03 and thus the Boost types.

I do, however, have a few ideas for a hypothetical Boost.Log 3.x, which would among other things switch to a more modern C++ version (most likely, C++17 or later). Unfortunately, this is nothing more than ideas and I don't know when I will be able to start working on it more seriously.

**Comment by quixoticaxis** [comment]
@Lastique thank you for your response.
