### ISSUE TITLE
link error macOS

### ISSUE THREAD

**Issue by ohhmm** [boostorg/log#62]
Undefined symbols for architecture x86_64:
  "boost::log::v2s_mt_posix::attribute_set::insert(boost::log::v2s_mt_posix::attribute_name, boost::log::v2s_mt_posix::attribute const&)", referenced from:
      boost::log::v2s_mt_posix::sources::basic_logger<char, boost::log::v2s_mt_posix::sources::severity_logger<boost::log::v2s_mt_posix::trivial::severity_level>, boost::log::v2s_mt_posix::sources::single_thread_model>::add_attribute_unlocked(boost::log::v2s_mt_posix::attribute_name const&, boost::log::v2s_mt_posix::attribute const&)

**Comment by Lastique** [comment]
Are you linking with a shared library and forgot to define `BOOST_LOG_DYN_LINK` or `BOOST_ALL_DYN_LINK`?

**Comment by ohhmm** [comment]
with cmake defaults

**Comment by Lastique** [comment]
I don't know what that means. Please, verify whether my suggestion works or not.

**Comment by Lastique** [comment]
No response.

**Comment by ohhmm** [comment]
Your suggestion works.
