### ISSUE TITLE
Linker/visibility warnings on macOS for boost log 1.68.0

### ISSUE THREAD

**Issue by lmcgrath** [boostorg/log#65]
I'm trying to compile boost 1.68.0 from source for a project on macOS and I'm getting a [pile of linker warnings](https://pastebin.com/DgtpYHdN). The warnings go away when I compile my project with `-fvisibility=hidden` (as expected) however, my project is multi-module and the library dependent on boost must itself be visible to a few other libraries and executables.

What's going on here? Is there a way to address these errors?

Here's my configure and build commands:

```
./bootstrap.sh
      --prefix=some/prefix/in/my/build/folder
      --with-libraries=filesystem
      --with-libraries=locale
      --with-libraries=log
      --with-libraries=system
      --with-libraries=thread

./b2 install
      cxxstd=17 # because boost_system barfs when trying to link cxx17 code
      link=shared # I've also tried static
      variant=release
      threading=multi
      runtime-link=shared # I even tried static here just to see what would happen
```

And I'm linking these libraries:
`boost_system, boost_thread, boost_filesystem, boost_locale, boost_log_setup, boost_log`

**Comment by Lastique** [comment]
Boost.Log is always built with hidden visibility. As far as I can tell, the warning says that Boost.Log code uses direct access to its symbols, so they won't be overridden at run time, which is the intention.

My advice would be to use hidden visibility everywhere, including your modules. Mark the symbols you need to export explicitly, with default visibility attributes or pragmas.

**Comment by lmcgrath** [comment]
Is there any particular reason I _don't_ need to do this with a package-installed binary of Boost.Log?

**Comment by Lastique** [comment]
Sorry, I have no idea. I don't use Mac OS and I don't know how the packages are built there.

The first Boost.Log release which had hidden visibility enabled was 1.59, so if your system packages are older, they were likely compiled with default visibility.

**Comment by Lastique** [comment]
Also, you might want to ensure that you're not linking with shared library when you build against the system libraries. In that case you probably won't get the warnings.

**Comment by lmcgrath** [comment]
I was using 1.66.0 previously installed through homebrew, so I don't know why that's different given what you've said. I think I've got enough info to sort out how my project needs to build given the visibility requirements, though, and thanks 👍
