### ISSUE TITLE
Rotating Log writes to original file?

### ISSUE THREAD

**Issue by linuxjh** [boostorg/log#67]
Can Boost Log write data always to the original file.
And the old data stored in file with name with pattern.

So the newly added log data can always be checked via tail like this:
  $ tail -f ~/message.log  
  (like: tail -f /var/log/message)

Old data stored when it reach limit in file with pattern:
  ~/old_log/message_20181206_113059_00001.log

**Comment by Lastique** [comment]
No, this behavior is currently not supported. The file name is generated once, when the file is created, not when the file is rotated (therefore the timestamp in the file name corresponds to the file creation).

**Comment by linuxjh** [comment]
Thanks!

I have some more questions.

Can I set a directory for log file (its name given by file_name) like I can set target for rotated log file. Or does it always write log file under the current working directory?

I used to print program log to stdout and redirect log with nohup. I tried the logrotate utility (without copytruncate). When it rotates log, the original file becomes zero bytes. Maybe it caused by me not setuping pre- script and not responding in my program to HUP signal sent from pre- spript.

I made a convenient macro around your Log library:
BLOG(info) << "An informational severity message";
BLOG(error) << "An error severity message";

It generated nice log like this:
2: [20181203 175935.575466] <info> - a.cpp:130 (main): An informational severity message
3: [20181203 175935.575473] <warning> - a.cpp:131 (main): A warning severity message

**Comment by Lastique** [comment]
> Can I set a directory for log file (its name given by file_name) like I can set target for rotated log file.

Yes. If you're using the `add_file_log` helper, you can specify the target directory in the `target` named parameter. If you're configuring sinks manually, you can set the target directory by configuring a file collector. See [here](https://www.boost.org/doc/libs/1_68_0/libs/log/doc/html/log/detailed/sink_backends.html#log.detailed.sink_backends.text_file.managing_rotated_files).

> I used to print program log to stdout and redirect log with nohup. I tried the logrotate utility (without copytruncate). When it rotates log, the original file becomes zero bytes.

The sink will not reopen or recreate the log file until it is rotated. So, after you or logrotate deletes the file that is currently being written, all subsequent log records will be lost until the rotation.

If you want to rotate log files on external events, such as `SIGHUP`, you should call `rotate_file` on the sink backend when you register that event. Note that you cannot call that function in a signal handler, you'll have to call it after you return from the signal handler.

**Comment by linuxjh** [comment]
Hi Andrey,

I meant the directory for the current file beeing written before its been rotated (not the target parameter). Can I set the directory for the current log file?

And are LineID & RecordID the same thing?

**Comment by Lastique** [comment]
> Can I set the directory for the current log file?

Yes, the directory can be part of the path you specify in the `file_name` parameter.

> And are LineID & RecordID the same thing?

Depends on what you mean by them. The library itself does not put any meaning in attributes, except for `Message`.

**Comment by Lastique** [comment]
https://www.boost.org/doc/libs/1_68_0/libs/log/doc/html/log/rationale/why_weak_record_ordering.html
