### ISSUE TITLE
build issues with avx2 now required

### ISSUE THREAD

**Issue by btiplitz** [boostorg/log#70]
The compiler detection when upgrading from 1.65 to 1.68, now sets the flag compiler-supports-avx2 which is then used to build in avx2 instructions into the library within the log library. There appears to be no way to disable this other than modifying the log library (or changing the jam file after the failure).

I only noticed this as I upgraded to gcc-4.9.4 with C++11 support but the binutils does not support avx2 instructions, so I can't build boost 1.68 on the target host as delivered.

**Comment by btiplitz** [comment]
the compiler was not built with a new assembler so it does not support AVX2.  It appears the build system does not know that, but I've not figured out why.  gcc does not require a newer binutils

**Comment by Lastique** [comment]
> the compiler was not built with a new assembler so it does not support AVX2.

AFAIK, the compiler will support AVX2 even if binutils don't. The "support" being the ability to translate compiler intrinsics into assembler instructions.

I think I've found the reason why your config could have passed the compiler check. I've committed 3e6fee4 to mitigate this.

**Comment by btiplitz** [comment]
Thanks -  I see if that mitigates the issue.  It appears the avx2 code won't run if built with avx2, but then run on a system without it.  Is that correct ?

**Comment by Lastique** [comment]
Yes, AVX2 will only execute on CPUs that support it. On CPUs that don't another code branch will execute.
