### ISSUE TITLE
use simple_event_log_backend, build in mingw failed

### ISSUE THREAD

**Issue by yuwenyong** [boostorg/log#74]
failed in link phase. Do I need to link any specific dll?

**Comment by Lastique** [comment]
You'll have to provide more details.

**Comment by Lastique** [comment]
Are the errors related to event log the only linking errors you get? If so, most likely Boost.Log was built without event log support. See if `b2` output contains a line `- message-compiler` in the beginning. If it says `no` then you don't have a message compiler tool in your `PATH` that is compatible with Boost.Build.

**Comment by yuwenyong** [comment]
These are the only errors.
I install boost by running command "pacman -S mingw-w64-x86_64-boost". BOOST_LOG_WITHOUT_EVENT_LOG is not defined.
It seems I have to build compile boost manually?

**Comment by Lastique** [comment]
I don't know what `pacman` is. If this is some kind of a package manager, find out how the package was built. Or build Boost yourself.

Though I have to say I remember there were problems with using `windmc` tool from MinGW with Boost.Build. I remember a few years back Boost.Build had to be patched to work with that tool, but I can't find a reference to the patch right now. This might be the reason why the package was built without event log support.

**Comment by Lastique** [comment]
See [here](https://www.boost.org/doc/libs/1_69_0/libs/log/doc/html/log/installation.html#log.installation.supported_compilers.notes_for_mingw__cygwin_and_visual_studio_express_edition_users) and [here](https://svn.boost.org/trac10/ticket/4111).

**Comment by yuwenyong** [comment]
Okay. I'm just wondering why BOOST_LOG_WITHOUT_EVENT_LOG is still undefined when mc tool can't be detected.

**Comment by Lastique** [comment]
Also, I should note that `BOOST_LOG_WITHOUT_EVENT_LOG` is a config macro, meaning that users can define it to disable event log support. The library defines it as part of its build process if it detects that event log cannot be supported. This macro is not defined by the library as a means to let users know that event log is not supported.
