### ISSUE TITLE
Boost.Log How to config current logging path

### ISSUE THREAD

**Issue by leoleung2000** [boostorg/log#89]
I have a application installed at ProgramFile folder , and the file collector target path be ProgramData. It is fine when the OS is under winXP. 

However, after migrated to Win10, my program cannot write any log because of privileges problem. 
How can i define all the logging file location be the "ProgramData" instead of "current path" ? 

```
// add file sink
auto file_sink = boost::make_shared< sinks::synchronous_sink<sinks::text_file_backend> >(
keywords::file_name = "Logging_Op%N.log", 
keywords::rotation_size = 5 * 1024 * 1024,
keywords::open_mode = std::ios_base::app | std::ios_base::out,
keywords::filter = channel == "general" );

file_sink->locked_backend()->set_file_collector(sinks::file::make_collector(
keywords::target = "C:\\ProgramData\\MyApplication\\", // 
keywords::max_size = 2 * 10* 5 * 1024 * 1024));
```

**Comment by Lastique** [comment]
> How can i define all the logging file location be the "ProgramData" instead of "current path" ?

You can include the path in the `file_name` named parameter.
